/* qS[A]/matches polyfill | @version 1.0 | MIT License | github.com/termi */
;(function(){"use strict";
var i=void 0,k=!0,q=null,s=!1,v=window;function A(){throw Error("SYNTAX_ERR");}
function ba(a,c,e,h,d,l,r,y,f){var P=e||[],t=!!d,B=!t&&c&&"number"==typeof c.length&&c.nodeType===i,m=t&&(c={})||(!c?document:B?c[0]:c),D,Q=0,b,w,j,J=ca[(a[1]||"").replace(da,"")]||0,aa=2<J,E=a[2],R=!!E,F=a[3],L=!!F,G=a[4],M=!!G,ka="*"===E,u,S,z,x,g,n,C,la,H,ma,p,N;if(R)if(E=ka?q:E.replace("|",":")){if(z=m)z=(z=m&&(m.ownerDocument||m).documentElement)?"HTML"!==z.nodeName:s;(n=z)||(E=E.toUpperCase())}else R=s;if(M&&(G=G.replace(ea," "),!I||1!==J))la=RegExp(G.replace(K,fa));if(z=a[5]){z=ga.call(z,"][");
for(u=-1;x=z[++u];)if((z[u]=x=x.match(ha))||A(),x[0]=x.input=x.index=q,x[2]=ia[x[2]],(p=x[3])&&" i"==p.substr(p.length-2))x[3]=p.substr(0,p.length-2),x[4]=k}if(a=a[6]){a=ga.call(a,":");for(u=-1;g=a[++u];)if((a[u]=g=g.match(ja))||A(),g[0]=g.input=g.index=q,p=g[1]=na[g[1]],2>p&&g[2])oa.test(g[2])?"even"===g[2]?g[2]=[q,2]:"odd"===g[2]?g[2]=[q,2,"%",1]:(g[2]=g[2].match(pa),g[2][0]=q):g[2]=[q,0,"%",g[2]],g[3]=p?"nodeIndexLast":"nodeIndex",g[4]=p?"lastChild":"firstChild",g[5]=p?"previousSibling":"nextSibling";
else if(17===p)f||A(),t=k,d=B?c:[c],a[u]=q;else if(12==p&&(n=g[2]))qa.test(n.charAt(0))&&qa.test(n.charAt(n.length-1))&&(g[2]=n.substr(1,n.length-2));1==a.length&&a[0]===q&&(a=q)}t&&(J=0);if(1==J)if(L){L=9===m.nodeType?m:m.ownerDocument;if(ra){d=L.getElementsByName(F);H=[];for(u=-1;b=d[++u];)b.id==F&&H.push(b)}else{H=[];for(d=[];b=L.getElementById(F);)d.push(b),n="id"in b?b.id:b.getAttribute("id"),n==F&&H.push(b),b.setAttribute("id",F+" _");for(u=-1;b=d[++u];)b.setAttribute("id",F)}d=q;L=s}else M=
M&&!I,R=R&&I&&!!G;t=(!B||1===c.length)&&!r&&!h&&!z&&!a&&!R&&!M&&!L&&!y;do{switch(J){case 0:b=d[0];break;case 1:if(F)if(d=[],H.length)if(1<H.length)for(u=-1;b=H[++u];){if(9===m.nodeType||m.contains(b))d.push(b),H.splice(u--,1)}else d=H;else return P;else"BODY"===E&&9===m.nodeType?(d=[m.body],M=!!G,t=t&&!M):d=!G||!I?m.getElementsByTagName(E||"*"):"getElementsByClassName"in m?m.getElementsByClassName(G):I.call(m,G);b=d[0];break;case 2:d=m.children;b=d[0];break;case 3:D=c[Q+1];case 4:if(!(b=O(m)))continue}if(t)return d;
B=0;if(b){do if((!ka||1===b.nodeType)&&(T?!(h&&(S=b[U])in e):!r||((S=b[U])?!(S in r):S=b[U]=++sa))){if(f=!(R&&(w=b.nodeName.toUpperCase())!==E||L&&b.id!==F||M&&(!b.className||!la.test(b.className)))){if(z)for(u=-1;f&&(x=z[++u]);)if(n=x[2],j=ta(b,x[1]),j===q)f=8===n;else switch(x[4]&&(j=j.toUpperCase()),C=x[3],n){case 1:f=!!j||""===j;break;case 2:f=j===C;break;case 3:case 8:f=RegExp("(^| +)"+C+"($| +)").test(j);8===n&&(f=!f);break;case 4:case 5:case 6:p=j.indexOf(C);f=6===n?!!~p:5===n?p==j.length-
C.length:!p;break;case 7:f=j===C||!!~j.indexOf(C+"-");break;case 9:f=!!~(" "+j.replace(ua," ")+" ").indexOf(" "+C+" ")}if(f&&a)for(u=-1;f&&(g=a[++u]);)switch(n=g[1],n){case 0:case 1:if(!n&&!g[3])break;C=g[3];j=g[4];ma=g[5];g=g[2];N=b[C]||0;n=g[3]?("%"===g[2]?-1:1)*g[3]:0;p=g[1];if(N)f=!p?!(N+n):!((N+n)%p);else{f=s;j=b.parentNode[j];do if(1==j.nodeType&&(j[C]=++N)&&b===j&&(!p?!(N+n):!((N+n)%p)))f=k;while(!f&&(j=j[ma]))}break;case 2:case 3:for(j=b;(j=j.previousSibling)&&1!==j.nodeType;);f=!j;if(!f||
3==n){for(;(j=aa?4===J?q:b===D?q:O(b):d[++B])&&j.parentNode==b.parentNode;);!aa&&4!==J&&--B;break}case 4:f=!O(b);break;case 5:f="HTML"==(w||b.nodeName.toUpperCase());break;case 6:f=!b.firstChild;break;case 7:f=!!b.checked;break;case 8:f=b.lang==g||b.ownerDocument.documentElement.lang==g;break;case 9:case 10:f="disabled"in b&&"form"in b&&(10==n?b.disabled===k&&"hidden"!==b.type:b.disabled===s);break;case 11:f=b.parentNode.selectedIndex&&!!b.selected;break;case 12:f=!!~(b.textContent||b.data||b.innerText||
b.nodeValue||b.value||"").indexOf(g[2]);break;case 13:case 14:f=va.call(b,g[2]);13==n&&(f=!f);break;case 15:case 16:w||(w=b.nodeName.toUpperCase());f=("INPUT"==w||"TEXTAREA"==w||wa.call(b.__getAttribute__||b.getAttribute,b,"contenteditable")!==q)&&!b.b;16==n&&(f=!f);break;case 18:f=b==m.ownerDocument.activeElement;break;default:A()}}if(f){if(l)return[b];if(y){P[Q]=b;break}else h?P[S]=b:(r&&(r[S]=k),P.push(b))}w=q}while(b=aa?4===J?q:b===D?q:O(b):d[++B])}b=q}while(m=c[++Q]);return P}
function xa(a,c,e){var h=!!e&&9===this.nodeType,d=[],l,r,y,f,e=h?e:this;if(ya)try{if(h&&V)return W(ya.call(this,a,e));y=(r="number"==typeof e.length&&e.nodeType===i)?e[0]:e;f=0;do{if(c)return[(9===y.nodeType?za:Aa).call(y,a)];l=(9===y.nodeType?ya:Ba).call(y,a);l.length&&(d=r?d.concat(Ca.call(l)):l)}while(r&&(y=e[++f]));return W(d)}catch(P){d=[]}var a=Da.call(a.replace(Ea,"$1")),t,B,m=k;y=s;var D;f=!!document.querySelector.__noorder__||!!document.querySelectorAll.__noorder__;var Q=a.replace(Fa,"@=").replace(Ga,
Ha).match(Ia),b,w,j;for(l=e;t=Q.shift();){h=Q[0];r=!h||","===h.charAt(0);!T&&(h&&1<h.length&&!B)&&(B={});if(!y)if(m&&"nodeType"in e&&9===e.nodeType&&"BODY"===t.toUpperCase())l=[e.body],r&&(d=l);else if(m&&":root"===t)l=[(9===e.nodeType?e:e.ownerDocument).documentElement],r&&(d=l);else if(l&&(!(e=l)||0===l.length))l=q,y=k;else{D=r&&(D||!!h||1<e.length);l=!f&&T&&D;l=(t=t.match(Ja))?ba(t,e,r&&!b?d:[],l,q,c&&r&&!b,!T&&(r&&B||!m&&1<e.length&&{}),b,m):[];if(b){for(j=w.length;0<j--;)l[j]||(l.splice(j,1),
w.splice(j,1));if(r&&w.length){if(c)return w[0];d=d.concat(w)}}if(t&&t[7]!==i&&l.length&&!r){b&&A();b=k;w=[];m=-1;for(j=l.length;++m<j;)w.push(l[m])}(","===a||!t)&&A()}if(c&&r&&l.length)return l[0];if(m=r)!d.length&&l&&(D=s,d=W(l)),l=q,e=this,y=s,b&&(w=b=i);if(!h||","===h)break}!T&&D&&d.sort(Ka);return D?W(d,k):d}function Ka(a,c){return a===c?0:a.compareDocumentPosition(c)&4?-1:1}v.Element||((v.Element=ActiveXObject).prototype.ie=k);v.HTMLElement||(v.HTMLElement=v.Element);v.Node||(v.Node=v.Element);
var X=v.Element.prototype,K=/\s*(\S+)\s*/g,fa="(?=(^|.*\\s)$1(\\s|$))",La=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,Ea=/\s*([,>+~\s])\s*/g,Fa=/~=/g,Ia=/(^|,|>|\+|~|\s).*?(?=[,>+~\s]|$)/g,ea=/\./g,ua=/\s/g,Ja=/^([,>+~\s])?([\w\-\|\*]*)#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?::([^!]+))?(!)?$/,ha=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$@!]?=)['"]?(.*?)['"]?)?\]?$/,ja=/^([^(]+)(?:\((.+)\))?$/,Ga=/\-child\((\dn)\+(\d)\)/g,Ha="-child\\($1%$2\\)",pa=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,Ma=/([,>+~\s])/,Na=/^\s+/,
da=/\s/,oa=/\D/,qa=/['"]/,ca={"":1,",":1,">":2,"~":3,"+":4},ia={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},na={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16,scope:17,focus:18,"nth-match":19,column:20,"nth-column":21},Oa={checked:q,disabled:q,ismap:q,multiple:q,readonly:q,selected:q},Pa={value:"defaultValue",checked:"defaultChecked",
selected:"defaultSelected"},Y=document.documentElement;function W(a,c){var e=a.length>>>0,h=new Z,d;if(!c){try{d=Ca.call(a),d.splice(0,0,h.length,0),h.splice.apply(h,d)}catch(l){}if(h&&h.length===e)return h}for(d=0;d<e;++d)d in a&&h.push(a[d]);return h}var ra,Qa=s,Ra="_"+Math.random(),Sa=document.createElement("br");Y.appendChild(Sa).id=Ra;try{Qa=document.getElementsByName(Ra)[0].id===Ra}catch(Ta){Qa=s}Y.removeChild(Sa);ra=Qa;
var U="sourceIndex",T=U in Y&&!("opera"in v),sa=1,O="nextElementSibling"in Y?function(a){return a.nextElementSibling}:function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a},Da=String.prototype.trim||function(){for(var a=this.replace(Na,""),c=a.length;da.test(a.charAt(--c)););return a.slice(0,c+1)},ga=String.prototype.split,Ca=Array.prototype.slice,Ua,$,I=($=Y.getElementsByClassName)&&80>($+"").length&&$,Z,va,ta,wa=Function.prototype.call,Aa=Y.querySelector,Ba=Y.querySelectorAll,za=document.querySelector,
ya=document.querySelectorAll,V=s,Va,Wa=document.createElement("input");Wa.setAttribute("value",5);Va=5!=Wa.defaultValue;za&&($=document.createElement("b"),$.a="_"+ +new Date,$.innerHTML="<i id='"+$.a+"'>t</i>",(V=za.call(document,"#"+$.a,$))&&(V="t"==V.innerHTML)||(V=s));Z=function(){};Z.prototype=[];$=new Z;$.push(1);
!$.length&&!("NodeList"in v)&&($=document.createElement("iframe"),$.style.display="none",document.body.appendChild($),$.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),Z=v.NodeList);T||(U="uniqueId");I||(Ua=function(a){a+="";if(this.querySelectorAll)try{return W(this.querySelectorAll(a.replace(K,".$1")))}catch(c){}var e=[],h=this.all,d,l=-1;if(h.length)for(a=RegExp(a.replace(K,fa));d=h[++l];)d.className&&a.test(d.className)&&e.push(d);return e});
ta=Va?function(a,c){c=c.toLowerCase();return Pa[c]!==i?a[Pa[c]]||"":s[c]!==i?a.getAttribute(c,2)||"":Oa[c]!==i?a.getAttribute(c)?c:"":(a=a.getAttributeNode(c))&&a.value||""}:function(a,c){return a.getAttribute(c)};
va=Y.matches||Y.webkitMatchesSelector||Y.mozMatchesSelector||Y.msMatchesSelector||Y.oMatchesSelector||"querySelector"in document?function(a){if(!a)return s;if("*"===a||":root"===a&&this===Y||"body"===a&&this===document.body)return k;var c,e,h=s;if(!Ma.test(a)&&(c=this.parentNode)&&"querySelector"in c)h=c.querySelector(a),h!==q&&(h=h===this);if(!h&&h!==q&&(c=this.ownerDocument))for(e in a=c.querySelectorAll(a),a)if(Object.prototype.hasOwnProperty.call(a,e)&&(h=a[e]===this))return k;return!!h}:function(a){if(!a)return s;
if("*"===a||this===Y&&":root"===a||this===document.body&&"BODY"===a.toUpperCase())return k;var c,e,h=s,d,a=Da.call(a);if(c=a.match(La))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return h=!(e=c[2])||this.className&&RegExp(e.replace(ea," ").replace(K,fa)).test(this.className),!!(h&&!(e=c[1])||this.tagName&&this.tagName.toUpperCase()===e.toUpperCase())}else{if(Ma.test(a)){e=xa.call(this.ownerDocument,a);for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)&&(h=e[d]===this))return k;
return s}e=ba(a.match(Ja),q,q,s,this,k);return e[0]===this}};$="matchesSelector";Y[$]||(X.matches=Y.matches=X[$]=Y[$]=va);$="matches";$ in X||(X[$]=document.documentElement[$]=X.matchesSelector);$="querySelectorAll";X[$]=Y[$]=document[$]=function(a,c){return xa.call(this,a,s,c)};$="querySelector";X[$]=Y[$]=document[$]=function(a,c){return xa.call(this,a,k,c)||q};$="getElementsByClassName";document[$]||(X[$]=Y[$]=document[$]=Ua);X=$=q;
})();
