/* @license qS[A]/matches polyfill | @version 1.0 | MIT License | github.com/termi */
;(function(){
var d=!0,j=null,s=!1,u=window;function w(){throw Error("SYNTAX_ERR");}
function aa(a,c,e,i,g,k,t,z,f){var O=e||[],q=!!g,x=!q&&c&&"number"==typeof c.length&&void 0===c.nodeType,n=q&&(c={})||(!c?document:x?c[0]:c),P,B=0,b,y,l,J=ba[(a[1]||"").replace(ca,"")]||0,V=2<J,E=a[2],Q=!!E,F=a[3],K=!!F,G=a[4],L=!!G,da="*"===E,r,W,A,v,h,m,D,ea,H,fa,p,M;if(Q)if(E=da?j:E.replace("|",":")){if(A=n)A=(A=n&&(n.ownerDocument||n).documentElement)?"HTML"!==A.nodeName:s;(m=A)||(E=E.toUpperCase())}else Q=s;if(L&&(G=G.replace(ga," "),!C||1!==J))ea=RegExp(G.replace(I,N));if(A=a[5]){A=ha.call(A,
"][");for(r=-1;v=A[++r];)if((A[r]=v=v.match(ia))||w(),v[0]=v.input=v.index=j,v[2]=ja[v[2]],(p=v[3])&&" i"==p.substr(p.length-2))v[3]=p.substr(0,p.length-2),v[4]=d}if(a=a[6]){a=ha.call(a,":");for(r=-1;h=a[++r];)if((a[r]=h=h.match(ka))||w(),h[0]=h.input=h.index=j,p=h[1]=la[h[1]],2>p&&h[2])ma.test(h[2])?"even"===h[2]?h[2]=[j,2]:"odd"===h[2]?h[2]=[j,2,"%",1]:(h[2]=h[2].match(na),h[2][0]=j):h[2]=[j,0,"%",h[2]],h[3]=p?"nodeIndexLast":"nodeIndex",h[4]=p?"lastChild":"firstChild",h[5]=p?"previousSibling":
"nextSibling";else if(17===p)f||w(),q=d,g=x?c:[c],a[r]=j;else if(12==p&&(m=h[2]))oa.test(m.charAt(0))&&oa.test(m.charAt(m.length-1))&&(h[2]=m.substr(1,m.length-2));1==a.length&&a[0]===j&&(a=j)}q&&(J=0);if(1==J)if(K){K=9===n.nodeType?n:n.ownerDocument;if(pa){g=K.getElementsByName(F);H=[];for(r=-1;b=g[++r];)b.id==F&&H.push(b)}else{H=[];for(g=[];b=K.getElementById(F);)g.push(b),m="id"in b?b.id:b.getAttribute("id"),m==F&&H.push(b),b.setAttribute("id",F+" _");for(r=-1;b=g[++r];)b.setAttribute("id",F)}g=
j;K=s}else L=L&&!C,Q=Q&&C&&!!G;q=(!x||1===c.length)&&!t&&!i&&!A&&!a&&!Q&&!L&&!K&&!z;do{switch(J){case 0:b=g[0];break;case 1:if(F)if(g=[],H.length)if(1<H.length)for(r=-1;b=H[++r];){if(9===n.nodeType||n.contains(b))g.push(b),H.splice(r--,1)}else g=H;else return O;else"BODY"===E&&9===n.nodeType?(g=[n.body],L=!!G,q=q&&!L):g=!G||!C?n.getElementsByTagName(E||"*"):"getElementsByClassName"in n?n.getElementsByClassName(G):C.call(n,G);b=g[0];break;case 2:g=n.children;b=g[0];break;case 3:P=c[B+1];case 4:if(!(b=
R(n)))continue}if(q)return g;x=0;if(b){do if((!da||1===b.nodeType)&&!(i&&(W=b.sourceIndex)in e)){if(f=!(Q&&(y=b.nodeName.toUpperCase())!==E||K&&b.id!==F||L&&(!b.className||!ea.test(b.className)))){if(A)for(r=-1;f&&(v=A[++r]);)if(m=v[2],l=qa(b,v[1]),l===j)f=8===m;else switch(v[4]&&(l=l.toUpperCase()),D=v[3],m){case 1:f=!!l||""===l;break;case 2:f=l===D;break;case 3:case 8:f=RegExp("(^| +)"+D+"($| +)").test(l);8===m&&(f=!f);break;case 4:case 5:case 6:p=l.indexOf(D);f=6===m?!!~p:5===m?p==l.length-D.length:
!p;break;case 7:f=l===D||!!~l.indexOf(D+"-");break;case 9:f=!!~(" "+l.replace(ra," ")+" ").indexOf(" "+D+" ")}if(f&&a)for(r=-1;f&&(h=a[++r]);)switch(m=h[1],m){case 0:case 1:if(!m&&!h[3])break;D=h[3];l=h[4];fa=h[5];h=h[2];M=b[D]||0;m=h[3]?("%"===h[2]?-1:1)*h[3]:0;p=h[1];if(M)f=!p?!(M+m):!((M+m)%p);else{f=s;l=b.parentNode[l];do if(1==l.nodeType&&(l[D]=++M)&&b===l&&(!p?!(M+m):!((M+m)%p)))f=d;while(!f&&(l=l[fa]))}break;case 2:case 3:for(l=b;(l=l.previousSibling)&&1!==l.nodeType;);f=!l;if(!f||3==m){for(;(l=
V?4===J?j:b===P?j:R(b):g[++x])&&l.parentNode==b.parentNode;);!V&&4!==J&&--x;break}case 4:f=!R(b);break;case 5:f="HTML"==(y||b.nodeName.toUpperCase());break;case 6:f=!b.firstChild;break;case 7:f=!!b.checked;break;case 8:f=b.lang==h||b.ownerDocument.documentElement.lang==h;break;case 9:case 10:f="disabled"in b&&"form"in b&&(10==m?b.disabled===d&&"hidden"!==b.type:b.disabled===s);break;case 11:f=b.parentNode.selectedIndex&&!!b.selected;break;case 12:f=!!~(b.textContent||b.data||b.innerText||b.nodeValue||
b.value||"").indexOf(h[2]);break;case 13:case 14:f=S.call(b,h[2]);13==m&&(f=!f);break;case 15:case 16:y||(y=b.nodeName.toUpperCase());f=("INPUT"==y||"TEXTAREA"==y||sa.call(b.__getAttribute__||b.getAttribute,b,"contenteditable")!==j)&&!b.a;16==m&&(f=!f);break;case 18:f=b==n.ownerDocument.activeElement;break;default:w()}}if(f){if(k)return[b];if(z){O[B]=b;break}else i?O[W]=b:(t&&(t[W]=d),O.push(b))}y=j}while(b=V?4===J?j:b===P?j:R(b):g[++x])}b=j}while(n=c[++B]);return O}
function T(a,c,e){var i=!!e&&9===this.nodeType,g=[],k,t,z,f,e=i?e:this;if(ta)try{if(i&&ua)return U(ta.call(this,a,e));z=(t="number"==typeof e.length&&e.nodeType===j)?e[0]:e;f=0;do{if(c)return[(9===z.nodeType?va:wa).call(z,a)];k=(9===z.nodeType?ta:xa).call(z,a);k.length&&(g=t?g.concat(ya.call(k)):k)}while(t&&(z=e[++f]));return U(g)}catch(O){g=[]}var a=za.call(a.replace(Aa,"$1")),q,x=d;z=s;var n;f=!!document.querySelector.__noorder__||!!document.querySelectorAll.__noorder__;var P=a.replace(Ba,"@=").replace(Ca,
Da).match(Ea),B,b,y;for(k=e;q=P.shift();){i=P[0];t=!i||","===i.charAt(0);if(!z)if(x&&"nodeType"in e&&9===e.nodeType&&"BODY"===q.toUpperCase())k=[e.body],t&&(g=k);else if(x&&":root"===q)k=[(9===e.nodeType?e:e.ownerDocument).documentElement],t&&(g=k);else if(k&&(!(e=k)||0===k.length))k=j,z=d;else{n=t&&(n||!!i||1<e.length);k=!f&&n;k=(q=q.match(Fa))?aa(q,e,t&&!B?g:[],k,j,c&&t&&!B,s,B,x):[];if(B){for(y=b.length;0<y--;)k[y]||(k.splice(y,1),b.splice(y,1));if(t&&b.length){if(c)return b[0];g=g.concat(b)}}if(q&&
q[7]!==j&&k.length&&!t){B&&w();B=d;b=[];x=-1;for(y=k.length;++x<y;)b.push(k[x])}(","===a||!q)&&w()}if(c&&t&&k.length)return k[0];if(x=t)!g.length&&k&&(n=s,g=U(k)),k=j,e=this,z=s,B&&(b=B=void 0);if(!i||","===i)break}return n?U(g):g}u.Element||((u.Element=ActiveXObject).prototype.ie=d);u.HTMLElement||(u.HTMLElement=u.Element);u.Node||(u.Node=u.Element);
var X=u.Element.prototype,I=/\s*(\S+)\s*/g,N="(?=(^|.*\\s)$1(\\s|$))",Ga=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,Aa=/\s*([,>+~\s])\s*/g,Ba=/~=/g,Ea=/(^|,|>|\+|~|\s).*?(?=[,>+~\s]|$)/g,ga=/\./g,ra=/\s/g,Fa=/^([,>+~\s])?([\w\-\|\*]*)#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?::([^!]+))?(!)?$/,ia=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$@!]?=)['"]?(.*?)['"]?)?\]?$/,ka=/^([^(]+)(?:\((.+)\))?$/,Ca=/\-child\((\dn)\+(\d)\)/g,Da="-child\\($1%$2\\)",na=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,Ha=/([,>+~\s])/,Ia=/^\s+/,
ca=/\s/,ma=/\D/,oa=/['"]/,ba={"":1,",":1,">":2,"~":3,"+":4},ja={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},la={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16,scope:17,focus:18,"nth-match":19,column:20,"nth-column":21},Ja={checked:j,disabled:j,ismap:j,multiple:j,readonly:j,selected:j},Ka={value:"defaultValue",checked:"defaultChecked",
selected:"defaultSelected"},La={action:j,cite:j,codebase:j,data:j,href:j,longdesc:j,lowsrc:j,src:j,usemap:j},Y=document.documentElement;function U(a){for(var c=a.length>>>0,e=new Z,i=0;i<c;++i)i in a&&e.push(a[i]);return e}
var pa=d,R="nextElementSibling"in Y?function(a){return a.nextElementSibling}:function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a},za=String.prototype.trim||function(){for(var a=this.replace(Ia,""),c=a.length;ca.test(a.charAt(--c)););return a.slice(0,c+1)},ha=String.prototype.split,ya=Array.prototype.slice,Ma,$,C=j,Z,S,qa,sa=Function.prototype.call,wa=Y.querySelector,xa=Y.querySelectorAll,va=document.querySelector,ta=document.querySelectorAll,ua=s,Na,Oa=document.createElement("input");
Oa.setAttribute("value",5);Na=5!=Oa.defaultValue;Z=function(){};Z.prototype=[];$=new Z;$.push(1);!$.length&&!("NodeList"in u)&&($=document.createElement("iframe"),$.style.display="none",document.body.appendChild($),$.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),Z=u.NodeList);C||(Ma=function(a){var c=[],e=this.all,i,g=-1;if(e.length)for(a=RegExp((a+"").replace(I,N));i=e[++g];)i.className&&a.test(i.className)&&c.push(i);return c});
qa=Na?function(a,c){c=c.toLowerCase();return void 0!==Ka[c]?a[Ka[c]]||"":void 0!==La[c]?a.getAttribute(c,2)||"":void 0!==Ja[c]?a.getAttribute(c)?c:"":(a=a.getAttributeNode(c))&&a.value||""}:function(a,c){return a.getAttribute(c)};
S=Y.matches||Y.webkitMatchesSelector||Y.mozMatchesSelector||Y.msMatchesSelector||Y.oMatchesSelector?function(a){if(!a)return s;if("*"===a||":root"===a&&this===Y||"body"===a&&this===document.body)return d;var c,e,i=s;if(!Ha.test(a)&&(c=this.parentNode)&&"querySelector"in c)i=c.querySelector(a),i!==j&&(i=i===this);if(!i&&i!==j&&(c=this.ownerDocument))for(e in a=c.querySelectorAll(a),a)if(Object.prototype.hasOwnProperty.call(a,e)&&(i=a[e]===this))return d;return!!i}:function(a){if(!a)return s;if("*"===
a||this===Y&&":root"===a||this===document.body&&"BODY"===a.toUpperCase())return d;var c,e,i=s,g,a=za.call(a);if(c=a.match(Ga))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return i=!(e=c[2])||this.className&&RegExp(e.replace(ga," ").replace(I,N)).test(this.className),!!(i&&!(e=c[1])||this.tagName&&this.tagName.toUpperCase()===e.toUpperCase())}else{if(Ha.test(a)){e=T.call(this.ownerDocument,a);for(g in e)if(Object.prototype.hasOwnProperty.call(e,g)&&(i=e[g]===this))return d;return s}e=
aa(a.match(Fa),j,j,s,this,d);return e[0]===this}};$="matchesSelector";Y[$]||(X.matches=Y.matches=X[$]=Y[$]=S);$="matches";$ in X||(X[$]=document.documentElement[$]=X.matchesSelector);$="querySelectorAll";X[$]=Y[$]=document[$]=function(a,c){return T.call(this,a,s,c)};$="querySelector";X[$]=Y[$]=document[$]=function(a,c){return T.call(this,a,d,c)||j};$="getElementsByClassName";document[$]||(X[$]=Y[$]=document[$]=Ma);X=$=j;
})();
