/* MIT License (c) copyright Egor Halimonenko (termi1uc1@gmail.com|github.com/termi) */
;(function(){"use strict";
var i=!0,j=null,q=!1,s=window;function v(){throw Error("SYNTAX_ERR");}
function aa(a,c,e,h,d,l,r,y,f){var O=e||[],t=!!d,B=!t&&c&&"number"==typeof c.length&&void 0===c.nodeType,m=t&&(c={})||(!c?document:B?c[0]:c),D,P=0,b,w,k,J=ba[(a[1]||"").replace(ca,"")]||0,$=2<J,E=a[2],Q=!!E,F=a[3],K=!!F,G=a[4],L=!!G,ja="*"===E,u,R,z,x,g,n,C,ka,H,la,p,M;if(Q)if(E=ja?j:E.replace("|",":")){if(z=m)z=(z=m&&(m.ownerDocument||m).documentElement)?"HTML"!==z.nodeName:q;(n=z)||(E=E.toUpperCase())}else Q=q;if(L&&(G=G.replace(da," "),!A||1!==J))ka=RegExp(G.replace(I,ea));if(z=a[5]){z=fa.call(z,
"][");for(u=-1;x=z[++u];)if((z[u]=x=x.match(ga))||v(),x[0]=x.input=x.index=j,x[2]=ha[x[2]],(p=x[3])&&" i"==p.substr(p.length-2))x[3]=p.substr(0,p.length-2),x[4]=i}if(a=a[6]){a=fa.call(a,":");for(u=-1;g=a[++u];)if((a[u]=g=g.match(ia))||v(),g[0]=g.input=g.index=j,p=g[1]=ma[g[1]],2>p&&g[2])na.test(g[2])?"even"===g[2]?g[2]=[j,2]:"odd"===g[2]?g[2]=[j,2,"%",1]:(g[2]=g[2].match(oa),g[2][0]=j):g[2]=[j,0,"%",g[2]],g[3]=p?"nodeIndexLast":"nodeIndex",g[4]=p?"lastChild":"firstChild",g[5]=p?"previousSibling":
"nextSibling";else if(17===p)f||v(),t=i,d=B?c:[c],a[u]=j;else if(12==p&&(n=g[2]))pa.test(n.charAt(0))&&pa.test(n.charAt(n.length-1))&&(g[2]=n.substr(1,n.length-2));1==a.length&&a[0]===j&&(a=j)}t&&(J=0);if(1==J)if(K){K=9===m.nodeType?m:m.ownerDocument;if(qa){d=K.getElementsByName(F);H=[];for(u=-1;b=d[++u];)b.id==F&&H.push(b)}else{H=[];for(d=[];b=K.getElementById(F);)d.push(b),n="id"in b?b.id:b.getAttribute("id"),n==F&&H.push(b),b.setAttribute("id",F+" _");for(u=-1;b=d[++u];)b.setAttribute("id",F)}d=
j;K=q}else L=L&&!A,Q=Q&&A&&!!G;t=(!B||1===c.length)&&!r&&!h&&!z&&!a&&!Q&&!L&&!K&&!y;do{switch(J){case 0:b=d[0];break;case 1:if(F)if(d=[],H.length)if(1<H.length)for(u=-1;b=H[++u];){if(9===m.nodeType||m.contains(b))d.push(b),H.splice(u--,1)}else d=H;else return O;else"BODY"===E&&9===m.nodeType?(d=[m.body],L=!!G,t=t&&!L):d=!G||!A?m.getElementsByTagName(E||"*"):"getElementsByClassName"in m?m.getElementsByClassName(G):A.call(m,G);b=d[0];break;case 2:d=m.children;b=d[0];break;case 3:D=c[P+1];case 4:if(!(b=
N(m)))continue}if(t)return d;B=0;if(b){do if((!ja||1===b.nodeType)&&(S?!(h&&(R=b[T])in e):!r||((R=b[T])?!(R in r):R=b[T]=++ra))){if(f=!(Q&&(w=b.nodeName.toUpperCase())!==E||K&&b.id!==F||L&&(!b.className||!ka.test(b.className)))){if(z)for(u=-1;f&&(x=z[++u]);)if(n=x[2],k=sa(b,x[1]),k===j)f=8===n;else switch(x[4]&&(k=k.toUpperCase()),C=x[3],n){case 1:f=!!k||""===k;break;case 2:f=k===C;break;case 3:case 8:f=RegExp("(^| +)"+C+"($| +)").test(k);8===n&&(f=!f);break;case 4:case 5:case 6:p=k.indexOf(C);f=
6===n?!!~p:5===n?p==k.length-C.length:!p;break;case 7:f=k===C||!!~k.indexOf(C+"-");break;case 9:f=!!~(" "+k.replace(ta," ")+" ").indexOf(" "+C+" ")}if(f&&a)for(u=-1;f&&(g=a[++u]);)switch(n=g[1],n){case 0:case 1:if(!n&&!g[3])break;C=g[3];k=g[4];la=g[5];g=g[2];M=b[C]||0;n=g[3]?("%"===g[2]?-1:1)*g[3]:0;p=g[1];if(M)f=!p?!(M+n):!((M+n)%p);else{f=q;k=b.parentNode[k];do if(1==k.nodeType&&(k[C]=++M)&&b===k&&(!p?!(M+n):!((M+n)%p)))f=i;while(!f&&(k=k[la]))}break;case 2:case 3:for(k=b;(k=k.previousSibling)&&
1!==k.nodeType;);f=!k;if(!f||3==n){for(;(k=$?4===J?j:b===D?j:N(b):d[++B])&&k.parentNode==b.parentNode;);!$&&4!==J&&--B;break}case 4:f=!N(b);break;case 5:f="HTML"==(w||b.nodeName.toUpperCase());break;case 6:f=!b.firstChild;break;case 7:f=!!b.checked;break;case 8:f=b.lang==g||b.ownerDocument.documentElement.lang==g;break;case 9:case 10:f="disabled"in b&&"form"in b&&(10==n?b.disabled===i&&"hidden"!==b.type:b.disabled===q);break;case 11:f=b.parentNode.selectedIndex&&!!b.selected;break;case 12:f=!!~(b.textContent||
b.data||b.innerText||b.nodeValue||b.value||"").indexOf(g[2]);break;case 13:case 14:f=ua.call(b,g[2]);13==n&&(f=!f);break;case 15:case 16:w||(w=b.nodeName.toUpperCase());f=("INPUT"==w||"TEXTAREA"==w||va.call(b.__getAttribute__||b.getAttribute,b,"contenteditable")!==j)&&!b.b;16==n&&(f=!f);break;case 18:f=b==m.ownerDocument.activeElement;break;default:v()}}if(f){if(l)return[b];if(y){O[P]=b;break}else h?O[R]=b:(r&&(r[R]=i),O.push(b))}w=j}while(b=$?4===J?j:b===D?j:N(b):d[++B])}b=j}while(m=c[++P]);return O}
function wa(a,c,e){var h=!!e&&9===this.nodeType,d=[],l,r,y,f,e=h?e:this;if(xa)try{if(h&&U)return V(xa.call(this,a,e));y=(r="number"==typeof e.length&&e.nodeType===j)?e[0]:e;f=0;do{if(c)return[(9===y.nodeType?ya:za).call(y,a)];l=(9===y.nodeType?xa:Aa).call(y,a);l.length&&(d=r?d.concat(Ba.call(l)):l)}while(r&&(y=e[++f]));return V(d)}catch(O){d=[]}var a=Ca.call(a.replace(Da,"$1")),t,B,m=i;y=q;var D;f=!!document.querySelector.__noorder__||!!document.querySelectorAll.__noorder__;var P=a.replace(Ea,"@=").replace(Fa,
Ga).match(Ha),b,w,k;for(l=e;t=P.shift();){h=P[0];r=!h||","===h.charAt(0);!S&&(h&&1<h.length&&!B)&&(B={});if(!y)if(m&&"nodeType"in e&&9===e.nodeType&&"BODY"===t.toUpperCase())l=[e.body],r&&(d=l);else if(m&&":root"===t)l=[(9===e.nodeType?e:e.ownerDocument).documentElement],r&&(d=l);else if(l&&(!(e=l)||0===l.length))l=j,y=i;else{D=r&&(D||!!h||1<e.length);l=!f&&S&&D;l=(t=t.match(Ia))?aa(t,e,r&&!b?d:[],l,j,c&&r&&!b,!S&&(r&&B||!m&&1<e.length&&{}),b,m):[];if(b){for(k=w.length;0<k--;)l[k]||(l.splice(k,1),
w.splice(k,1));if(r&&w.length){if(c)return w[0];d=d.concat(w)}}if(t&&t[7]!==j&&l.length&&!r){b&&v();b=i;w=[];m=-1;for(k=l.length;++m<k;)w.push(l[m])}(","===a||!t)&&v()}if(c&&r&&l.length)return l[0];if(m=r)!d.length&&l&&(D=q,d=V(l)),l=j,e=this,y=q,b&&(w=b=void 0);if(!h||","===h)break}!S&&D&&d.sort(Ja);return D?V(d,i):d}function Ja(a,c){return a===c?0:a.compareDocumentPosition(c)&4?-1:1}s.Element||((s.Element=ActiveXObject).prototype.ie=i);s.HTMLElement||(s.HTMLElement=s.Element);s.Node||(s.Node=s.Element);
var W=s.Element.prototype,I=/\s*(\S+)\s*/g,ea="(?=(^|.*\\s)$1(\\s|$))",Ka=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,Da=/\s*([,>+~\s])\s*/g,Ea=/~=/g,Ha=/(^|,|>|\+|~|\s).*?(?=[,>+~\s]|$)/g,da=/\./g,ta=/\s/g,Ia=/^([,>+~\s])?([\w\-\|\*]*)#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?::([^!]+))?(!)?$/,ga=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$@!]?=)['"]?(.*?)['"]?)?\]?$/,ia=/^([^(]+)(?:\((.+)\))?$/,Fa=/\-child\((\dn)\+(\d)\)/g,Ga="-child\\($1%$2\\)",oa=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,La=/([,>+~\s])/,Ma=/^\s+/,
ca=/\s/,na=/\D/,pa=/['"]/,ba={"":1,",":1,">":2,"~":3,"+":4},ha={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},ma={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16,scope:17,focus:18,"nth-match":19,column:20,"nth-column":21},Na={checked:j,disabled:j,ismap:j,multiple:j,readonly:j,selected:j},Oa={value:"defaultValue",checked:"defaultChecked",
selected:"defaultSelected"},X=document.documentElement;function V(a,c){var e=a.length>>>0,h=new Y,d;if(!c){try{d=Ba.call(a),d.splice(0,0,h.length,0),h.splice.apply(h,d)}catch(l){}if(h&&h.length===e)return h}for(d=0;d<e;++d)d in a&&h.push(a[d]);return h}var qa,Pa=q,Qa="_"+Math.random(),Ra=document.createElement("br");X.appendChild(Ra).id=Qa;try{Pa=document.getElementsByName(Qa)[0].id===Qa}catch(Sa){Pa=q}X.removeChild(Ra);qa=Pa;
var T="sourceIndex",S=T in X&&!("opera"in s),ra=1,N="nextElementSibling"in X?function(a){return a.nextElementSibling}:function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a},Ca=String.prototype.trim||function(){for(var a=this.replace(Ma,""),c=a.length;ca.test(a.charAt(--c)););return a.slice(0,c+1)},fa=String.prototype.split,Ba=Array.prototype.slice,Ta,Z,A=(Z=X.getElementsByClassName)&&80>(Z+"").length&&Z,Y,ua,sa,va=Function.prototype.call,za=X.querySelector,Aa=X.querySelectorAll,ya=document.querySelector,
xa=document.querySelectorAll,U=q,Ua,Va=document.createElement("input");Va.setAttribute("value",5);Ua=5!=Va.defaultValue;ya&&(Z=document.createElement("b"),Z.a="_"+ +new Date,Z.innerHTML="<i id='"+Z.a+"'>t</i>",(U=ya.call(document,"#"+Z.a,Z))&&(U="t"==U.innerHTML)||(U=q));Y=function(){};Y.prototype=[];Z=new Y;Z.push(1);
!Z.length&&!("NodeList"in s)&&(Z=document.createElement("iframe"),Z.style.display="none",document.body.appendChild(Z),Z.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),Y=s.NodeList);S||(T="uniqueId");A||(Ta=function(a){a+="";if(this.querySelectorAll)try{return V(this.querySelectorAll(a.replace(I,".$1")))}catch(c){}var e=[],h=this.all,d,l=-1;if(h.length)for(a=RegExp(a.replace(I,ea));d=h[++l];)d.className&&a.test(d.className)&&e.push(d);return e});
sa=Ua?function(a,c){c=c.toLowerCase();return void 0!==Oa[c]?a[Oa[c]]||"":void 0!==q[c]?a.getAttribute(c,2)||"":void 0!==Na[c]?a.getAttribute(c)?c:"":(a=a.getAttributeNode(c))&&a.value||""}:function(a,c){return a.getAttribute(c)};
ua=X.matches||X.webkitMatchesSelector||X.mozMatchesSelector||X.msMatchesSelector||X.oMatchesSelector||"querySelector"in document?function(a){if(!a)return q;if("*"===a||":root"===a&&this===X||"body"===a&&this===document.body)return i;var c,e,h=q;if(!La.test(a)&&(c=this.parentNode)&&"querySelector"in c)h=c.querySelector(a),h!==j&&(h=h===this);if(!h&&h!==j&&(c=this.ownerDocument))for(e in a=c.querySelectorAll(a),a)if(Object.prototype.hasOwnProperty.call(a,e)&&(h=a[e]===this))return i;return!!h}:function(a){if(!a)return q;
if("*"===a||this===X&&":root"===a||this===document.body&&"BODY"===a.toUpperCase())return i;var c,e,h=q,d,a=Ca.call(a);if(c=a.match(Ka))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return h=!(e=c[2])||this.className&&RegExp(e.replace(da," ").replace(I,ea)).test(this.className),!!(h&&!(e=c[1])||this.tagName&&this.tagName.toUpperCase()===e.toUpperCase())}else{if(La.test(a)){e=wa.call(this.ownerDocument,a);for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)&&(h=e[d]===this))return i;
return q}e=aa(a.match(Ia),j,j,q,this,i);return e[0]===this}};Z="matchesSelector";X[Z]||(W.matches=X.matches=W[Z]=X[Z]=ua);Z="matches";Z in W||(W[Z]=document.documentElement[Z]=W.matchesSelector);Z="querySelectorAll";W[Z]=X[Z]=document[Z]=function(a,c){return wa.call(this,a,q,c)};Z="querySelector";W[Z]=X[Z]=document[Z]=function(a,c){return wa.call(this,a,i,c)||j};Z="getElementsByClassName";document[Z]||(W[Z]=X[Z]=document[Z]=Ta);W=Z=j;
})();
