/* MIT License (c) copyright Egor Halimonenko (termi1uc1@gmail.com|github.com/termi) */
;(function(){
var f=void 0,m=!0,n=null,p=!1,t=window;
function w(a,c,e,g,h,z,k){var b=a.match(da)||[],a=e||[],l=!!h,o=l&&(c={})||(!c?document:"length"in c?c[0]:c),F,G=0,i,L=ea[b[1]||""]||0,la=2<L,H=b[2],M=!!H,A=b[3],P=!!A,D=b[4],I=!!D,$="*"===H,u,R,d,Q,r,B,y,j,E,aa,q,J,x,s,v,S,T,ba,ca;M&&(H=$?f:H.replace("|",":").toUpperCase());if(I&&(D=D.replace(fa," "),!C||1!==L))aa=RegExp(D.replace(K,N));l&&(L=0);if(l=b[5]){l=ga.call(l,"][");for(u=-1;r=l[++u];)if(r=l[u]=r.match(ha),r[2]=ia[r[2]],(s=r[3])&&" i"==ja.call(s,-2))r[3]=s.substr(0,s.length-2),r[4]=m}if(q=
b[6])q=q.match(ka),y=ma[q[1]],2>y&&q[2]&&(B=/\D/.test(q[2])?"even"===q[2]?[n,2]:"odd"===q[2]?[n,2,"%",1]:q[2].match(na):[n,0,"%",q[2]],T=y?"nodeIndexLast":"nodeIndex",ba=y?"lastChild":"firstChild",ca=y?"previousSibling":"nextSibling");if(1==L)if(P){if(oa){h=document.getElementsByName(A);J=[];for(u=-1;b=h[++u];)b.id==A&&J.push(b)}else{J=[];for(h=[];b=document.getElementById(A);)h.push(b),b.id==A&&J.push(b),b.setAttribute("id",A+" _");for(u=-1;b=h[++u];)b.setAttribute("id",A)}h=P=f}else I=I&&!C,M=M&&
C&&!!D;Q=(!("length"in c)||1===c.length)&&!g&&!l&&!q&&!M&&!I&&!P;do{b=f;switch(L){case 1:if(A)if(h=[],J.length)for(u=-1;b=J[++u];){if(o===document||o.contains(b))h.push(b),J.splice(u--,1)}else return a;else"BODY"===H&&9===o.nodeType?(h=[o.body],I=!!D,Q=Q&&!I):h=!D||!C?o.getElementsByTagName(H||"*"):o.getElementsByClassName(D);b=h[0];break;case 2:h=o.children;b=h[0];break;case 3:F=c[G+1];case 4:if(!(b=O(o)))continue}if(Q)return h;o=0;if(b){do if(!$||1===b.nodeType)if(!(g&&(R=b.sourceIndex)in e)){if(d=
!(M&&(i=b.nodeName.toUpperCase())!==H||P&&b.id!==A||I&&(!b.className||!aa.test(b.className)))){if(l){u=-1;for(S=b.attributes;d&&(r=l[++u])&&(d=(v=r[1])in S);)if(j=v in pa?pa[v](b):(j=S[v])&&(j.specified||v in qa)&&""!==j.nodeValue?j.nodeValue:n,x=r[2],j===n){if(!(d=8==x))d=p}else switch(r[4]&&(j=j.toUpperCase()),E=r[3],x){case 1:d=!!j||""===j;break;case 2:d=j===E;break;case 3:case 8:d=RegExp("(^| +)"+E+"($| +)").test(j);8==x&&(d=!d);break;case 4:case 5:case 6:s=j.indexOf(E);d=6===x?~s:5===x?s==j.length-
E.length:!s;break;case 7:d=j===E||!!~j.indexOf(E+"-");break;case 9:d=!!~(" "+j.replace(ra," ")+" ").indexOf(" "+E+" ")}}if(d&&q)switch(y){case 0:case 1:if(!B[1]&&!B[3])break;v=b[T]||0;x=B[3]?("%"===B[2]?-1:1)*B[3]:0;s=B[1];if(v)d=!s?!(v+x):!((v+x)%s);else{d=p;i=b.parentNode[ba];do if(1==i.nodeType&&(i[T]=++v)&&b===i&&(!s?!(v+x):!((v+x)%s)))d=m;while(!d&&(i=i[ca]))}break;case 2:case 3:for(i=b;(i=i.previousSibling)&&1!==i.nodeType;);d=!i;if(!d||3==y)break;case 4:d=!O(b);break;case 5:d="HTML"==(i||b.nodeName.toUpperCase());
break;case 6:d=!b.firstChild;break;case 7:d=!!b.checked;break;case 8:d=b.lang==B||U.lang==B;break;case 9:case 10:d="disabled"in b&&"form"in b&&(10==y?b.disabled===m&&"hidden"!==b.type:b.disabled===p);break;case 11:d=b.parentNode.selectedIndex&&!!b.selected;break;case 12:d=!!~(b.textContent||b.data||b.innerText||b.nodeValue||b.value||"").indexOf(q[2]);break;case 13:case 14:d=V.call(b,q[2]);13==y&&(d=!d);break;case 15:case 16:i||(i=b.nodeName.toUpperCase()),d=("INPUT"==i||"TEXTAREA"==i||b.getAttribute("contenteditable")!==
n)&&!b.a,16==y&&(d=!d)}}if(d){if(z)return[b];g?a[R]=b:(k&&(k[R]=m),a.push(b))}i=f}while(b=la?4===L?f:b===F?f:O(b):h[++o])}}while(o=c[++G]);return a}
function W(a,c,e){e||(e=this);for(var a=sa.call(a.replace(ta,"$1")),g=[],h,z=-1,k=e,b,l,o=m,F=p,G,i=!!document.querySelector.__noorder__||!!document.querySelectorAll.__noorder__,a=a.replace(ua,"@=").replace(va,"-child($1%$2)").match(wa);h=a[++z];){b=a[z+1];l=!b||","===b.charAt(0);if(!F)if(o&&"nodeType"in e&&9===e.nodeType&&"BODY"===h.toUpperCase())k=[e.body],l&&(g=k);else if(o&&":root"===h)k=[U],l&&(g=k);else if(k&&(!(e=k)||0===k.length))k=n,F=m;else if(!F){if(k=!i&&l&&(G||!!b||1<e.length))G=m;k=
w(h,e,l?g:[],k,n,c&&lastRul,p)}if(o=l)!g.length&&k&&(G=p,g=xa(k)),k=n,e=this,F=p;if(!b||","===b)break}return G?xa(g,m):g}t.Element||((t.Element=ActiveXObject).prototype.ie=m);t.HTMLElement||(t.HTMLElement=t.Element);t.Node||(t.Node=t.Element);
var X=t.Element.prototype,K=/\s*(\S+)\s*/g,N="(?=(^|.*\\s)$1(\\s|$))",ya=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,ta=/\s*([,>+~ ])\s*/g,ua=/\~\=/g,wa=/(^[>+~ ]?|,|\>|\+|~| ).*?(?=[,>+~ ]|$)/g,fa=/\./g,ra=/\s/g,da=/^([,>+~ ])?([\w\-\|\*]*)\#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?:\:(.+))?$/,ha=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$\@!]?=)['"]?(.*?)['"]?)?\]?$/,ka=/^([^(]+)(?:\(([^)]+)\))?$/,va=/\-child\((\dn)\+(\d)\)/g,na=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,za=/([,>+~ ])/,Aa=/^\s+/,Ba=/\s/,ea={"":1," ":1,
",":1,">":2,"~":3,"+":4},ia={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},ma={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16},pa={href:function(a){return a.getAttribute("href",2)}},qa={coords:1,id:1,name:1};
function xa(a,c){var e=a.length>>>0,g=new Y;if(!c){try{Ca.call(a)}catch(h){}if(g&&g.length===e)return g}for(var z=0;z<e;z++)z in a&&g.push(a[z]);return g}
var oa=m,U=document.documentElement,O="nextElementSibling"in U?function(a){return a.nextElementSibling}:function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a},sa=String.prototype.trim||function(){for(var a=this.replace(Aa,""),c=a.length;Ba.test(a.charAt(--c)););return a.slice(0,c+1)},ga=String.prototype.split,Da=String.prototype.substr,ja="b"=="ab".substr(-1)?String.prototype.substr:function(a,c){return Da.call(this,0>a?0>(a=this.length+a)?0:a:a,c)},Ea,C=p,Ca=Array.prototype.slice,Z,Y,V;
Y=function(){};Y.prototype=[];Z=new Y;Z.push(1);!Z.length&&!("NodeList"in t)&&(Z=document.createElement("iframe"),Z.style.display="none",document.body.appendChild(Z),Z.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),Y=t.NodeList);C||(Ea=function(a){var c=[],e=this.all,g,h=-1;if(e.length)for(a=RegExp((a+"").replace(K,N));g=e[++h];)g.className&&a.test(g.className)&&c.push(g);return c});
V=function(a){if(!a)return p;if(a==="*"||this===U&&a===":root"||this===document.body&&a.toUpperCase()==="BODY")return m;var c,e,g=p,h,a=sa.call(a);if(c=a.match(ya))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return(g=!(e=c[2])||this.className&&RegExp(e.replace(fa," ").replace(K,N)).test(this.className))&&!(e=c[1])||this.tagName&&this.tagName.toUpperCase()===e.toUpperCase()}else{if(za.test(a)){e=W.call(this.ownerDocument,a);for(h in e)if(Object.prototype.hasOwnProperty.call(e,
h))if(g=e[h]===this)return m;return p}e=w(a,n,p,n,this,m);return e[0]===this}};Z="matchesSelector";
U[Z]||(X.matches=U.matches=X[Z]=U[Z]=X[Z]=U.webkitMatchesSelector||U.mozMatchesSelector||U.msMatchesSelector||U.oMatchesSelector?function(a){if(!a)return p;if(a==="*"||a===":root"&&this===U||a==="body"&&this===document.body)return m;var c,e,g=p;if(!za.test(a)&&(c=this.parentNode)&&"querySelector"in c)g=c.querySelector(a)===this;if(!g&&(c=this.ownerDocument)){a=c.querySelectorAll(a);for(e in a)if(Object.prototype.hasOwnProperty.call(a,e))if(g=a[e]===this)return m}return g}:V);Z="matches";
Z in X||(X[Z]=document.documentElement[Z]=X.matchesSelector);Z="querySelectorAll";document[Z]||(X[Z]=U[Z]=document[Z]=function(a,c){return W.call(this,a,p,c)});Z="querySelector";document[Z]||(X[Z]=U[Z]=document[Z]=function(a,c){return W.call(this,a,m,c)[0]||n});Z="getElementsByClassName";document[Z]||(X[Z]=U[Z]=document[Z]=Ea);
})();
