/* MIT License (c) copyright Egor Halimonenko (termi1uc1@gmail.com|github.com/termi) */
;(function(){"use strict";
var g=void 0,n=!0,p=null,s=!1,t=window;
function aa(a,e,f,k,d,h,D,q,x){var O=f||[],c=!!d,y=!c&&e&&"number"==typeof e.length&&e.nodeType===g,m=c&&(e={})||(!e?document:y?e[0]:e),E,z=0,b,K,j,I=ba[a[1]||""]||0,$=2<I,L=a[2],P=!!L,F=a[3],Y=!!F,G=a[4],M=!!G,ia="*"===L,r,Q,u,i,l,A,ja,J,N,T,B,w;P&&((L=ia?g:L.replace("|",":").toUpperCase())||(P=s));if(M&&(G=G.replace(ca," "),!v||1!==I))ja=RegExp(G.replace(da,ea));if(J=a[5]){J=fa.call(J,"][");for(r=-1;u=J[++r];)if(u=J[r]=u.match(ga),u[0]=g,u[2]=ha[u[2]],(l=u[3])&&" i"==l.substr(l.length-2))u[3]=l.substr(0,
l.length-2),u[4]=n}if(a=a[6]){a=fa.call(a,":");for(r=-1;i=a[++r];)if(a[r]=i=i.match(ka),i[0]=g,l=i[1]=la[i[1]],2>l&&i[2])ma.test(i[2])?"even"===i[2]?i[2]=[g,2]:"odd"===i[2]?i[2]=[g,2,"%",1]:(i[2]=i[2].match(na),i[2][0]=g):i[2]=[g,0,"%",i[2]],i[3]=l?"nodeIndexLast":"nodeIndex",i[4]=l?"lastChild":"firstChild",i[5]=l?"previousSibling":"nextSibling";else if(17===l){if(!x)throw Error("SYNTAX_ERR");c=n;d=y?e:[e];a[r]=g}1==a.length&&a[0]===g&&(a=g)}c&&(I=0);if(1==I)if(Y){if(oa){d=document.getElementsByName(F);
N=[];for(r=-1;b=d[++r];)b.id==F&&N.push(b)}else{N=[];for(d=[];b=document.getElementById(F);)d.push(b),b.id==F&&N.push(b),b.setAttribute("id",F+" _");for(r=-1;b=d[++r];)b.setAttribute("id",F)}d=Y=g}else M=M&&!v,P=P&&v&&!!G;y=(!y||1===e.length)&&!k&&!J&&!a&&!P&&!M&&!Y&&!q;do{switch(I){case 0:b=d[0];break;case 1:if(F)if(d=[],N.length)for(r=-1;b=N[++r];){if(m===document||m.contains(b))d.push(b),N.splice(r--,1)}else return O;else"BODY"===L&&9===m.nodeType?(d=[m.body],M=!!G,y=y&&!M):d=!G||!v?m.getElementsByTagName(L||
"*"):"getElementsByClassName"in m?m.getElementsByClassName(G):v.call(m,G);b=d[0];break;case 2:d=m.children;b=d[0];break;case 3:E=e[z+1];case 4:if(!(b=C(m)))continue}if(y)return d;x=0;if(b){do if((!ia||1===b.nodeType)&&(H?!(k&&(Q=b[R])in f):!D||((Q=b[R])?!(Q in D):Q=b[R]=++pa))){if(c=!(P&&(K=b.nodeName.toUpperCase())!==L||Y&&b.id!==F||M&&(!b.className||!ja.test(b.className)))){if(J){r=-1;for(T=b.attributes;c&&(u=J[++r])&&(c=(w=u[1])in T);)if(j=w in qa?qa[w](b):(j=T[w])&&(j.specified||w in ra)&&""!==
j.nodeValue?j.nodeValue:p,B=u[2],j===p)c=8===B;else switch(u[4]&&(j=j.toUpperCase()),A=u[3],B){case 1:c=!!j||""===j;break;case 2:c=j===A;break;case 3:case 8:c=RegExp("(^| +)"+A+"($| +)").test(j);8===B&&(c=!c);break;case 4:case 5:case 6:l=j.indexOf(A);c=6===B?~l:5===B?l==j.length-A.length:!l;break;case 7:c=j===A||!!~j.indexOf(A+"-");break;case 9:c=!!~(" "+j.replace(sa," ")+" ").indexOf(" "+A+" ")}}if(c&&a)for(r=-1;c&&(i=a[++r]);)switch(l=i[1],l){case 0:case 1:if(!l&&!i[3])break;A=i[3];j=i[4];T=i[5];
i=i[2];w=b[A]||0;B=i[3]?("%"===i[2]?-1:1)*i[3]:0;l=i[1];if(w)c=!l?!(w+B):!((w+B)%l);else{c=s;j=b.parentNode[j];do if(1==j.nodeType&&(j[A]=++w)&&b===j&&(!l?!(w+B):!((w+B)%l)))c=n;while(!c&&(j=j[T]))}break;case 2:case 3:for(j=b;(j=j.previousSibling)&&1!==j.nodeType;);c=!j;if(!c||3==l){for(;(j=$?4===I?g:b===E?g:C(b):d[++x])&&j.parentNode==b.parentNode;);!$&&4!==I&&--x;break}case 4:c=!C(b);break;case 5:c="HTML"==(K||b.nodeName.toUpperCase());break;case 6:c=!b.firstChild;break;case 7:c=!!b.checked;break;
case 8:c=b.lang==i||S.lang==i;break;case 9:case 10:c="disabled"in b&&"form"in b&&(10==l?b.disabled===n&&"hidden"!==b.type:b.disabled===s);break;case 11:c=b.parentNode.selectedIndex&&!!b.selected;break;case 12:c=!!~(b.textContent||b.data||b.innerText||b.nodeValue||b.value||"").indexOf(a[2]);break;case 13:case 14:c=ta.call(b,a[2]);13==l&&(c=!c);break;case 15:case 16:K||(K=b.nodeName.toUpperCase());c=("INPUT"==K||"TEXTAREA"==K||ua.call(b.__getAttribute__||b.getAttribute,b,"contenteditable")!==p)&&!b.b;
16==l&&(c=!c);break;case 18:c=b==m.ownerDocument.activeElement;break;default:throw Error("SYNTAX_ERR");}}if(c){if(h)return[b];if(q){O[z]=b;break}else k?O[Q]=b:(D&&(D[Q]=n),O.push(b))}K=g}while(b=$?4===I?g:b===E?g:C(b):d[++x])}b=g}while(m=e[++z]);return O}
function va(a,e,f){var k=!!f&&this===document,d=[],h,D,q,x,f=k?f:this;if(wa)try{if(k&&U)return V(xa.call(document,a,f));q=(D="number"==typeof f.length&&f.nodeType===g)?f[0]:f;x=0;do if(h=(e?q==document?ya:wa:q==document?xa:za).call(q,a),e||h.length){if(e)return h;d=d.concat(Aa.call(h))}while(D&&(q=f[++x]));return V(d)}catch(O){d=[]}var a=Ba.call(a.replace(Ca,"$1")),c,y,m=n,k=s,E;D=!!document.querySelector.__noorder__||!!document.querySelectorAll.__noorder__;x=a.replace(Da,"@=").replace(Ea,"-child\\($1%$2\\)").match(Fa);
var z,b;for(h=f;c=x.shift();){a=x[0];q=!a||","===a.charAt(0);!H&&(a&&1<a.length&&!y)&&(y={});if(!k)if(m&&"nodeType"in f&&9===f.nodeType&&"BODY"===c.toUpperCase())h=[f.body],q&&(d=h);else if(m&&":root"===c)h=[S],q&&(d=h);else if(h&&(!(f=h)||0===h.length))h=p,k=n;else{if(h=!D&&H&&q&&(E||!!a||1<f.length))E=n;h=(c=c.match(Ga))?aa(c,f,q&&!z?d:[],h,p,e&&q&&!z,!H&&(q&&y||!m&&1<f.length&&{}),z,m):[];if(z){for(m=b.length;0<m--;)h[m]||(h.splice(m,1),b.splice(m,1));if(q&&b.length){if(e)return b[0];d=d.concat(b)}}if(c&&
c[7]!==g&&h.length&&!q){z=n;b=[];c=-1;for(m=h.length;++c<m;)b.push(h[c])}}if(e&&q&&h.length)return h[0];if(m=q)!d.length&&h&&(E=s,d=V(h)),h=p,f=this,k=s,z&&(b=z=g);if(!a||","===a)break}!H&&E&&d.sort(Ha);return E?V(d,n):d}function Ha(a,e){return a===e?0:a.compareDocumentPosition(e)&4?-1:1}t.Element||((t.Element=ActiveXObject).prototype.ie=n);t.HTMLElement||(t.HTMLElement=t.Element);t.Node||(t.Node=t.Element);
var W=t.Element.prototype,da=/\s*(\S+)\s*/g,ea="(?=(^|.*\\s)$1(\\s|$))",Ia=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,Ca=/\s*([,>+~ ])\s*/g,Da=/\~\=/g,Fa=/(^|,|\>|\+|~| ).*?(?=[,>+~ ]|$)/g,ca=/\./g,sa=/\s/g,Ga=/^([,>+~ ])?([\w\-\|\*]*)\#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?:\:([^!]+))?(!)?$/,ga=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$\@!]?=)['"]?(.*?)['"]?)?\]?$/,ka=/^([^(]+)(?:\\\((.+)\\\))?$/,Ea=/\-child\((\dn)\+(\d)\)/g,na=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,Ja=/([,>+~ ])/,Ka=/^\s+/,La=/\s/,ma=/\D/,
ba={"":1," ":1,",":1,">":2,"~":3,"+":4},ha={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},la={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16,scope:17,focus:18,"nth-match":19,column:20,"nth-column":21},qa={href:function(a){return ua.call(a.__getAttribute__||a.getAttribute,a,"href",2)}},ra={coords:1,id:1,name:1},S=document.documentElement;
function V(a,e){var f=a.length>>>0,k=new X;if(!e){try{Aa.call(a)}catch(d){}if(k&&k.length===f)return k}for(var h=0;h<f;h++)h in a&&k.push(a[h]);return k}var oa,Ma=s,Na="_"+Math.random(),Oa=document.createElement("br");S.appendChild(Oa).id=Na;try{Ma=document.getElementsByName(Na)[0].id===Na}catch(Pa){Ma=s}finally{S.removeChild(Oa)}oa=Ma;
var R="sourceIndex",H=R in S&&!("opera"in t),pa=1,C="nextElementSibling"in S?function(a){return a.nextElementSibling}:function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a},Ba=String.prototype.trim||function(){for(var a=this.replace(Ka,""),e=a.length;La.test(a.charAt(--e)););return a.slice(0,e+1)},fa=String.prototype.split,Qa,Z,v=(Z=S.getElementsByClassName)&&80>(Z+"").length&&Z,Aa=Array.prototype.slice,X,ta,ua=Function.prototype.call,wa=S.querySelector,za=S.querySelectorAll,ya=document.querySelector,
xa=document.querySelectorAll,U=s;wa&&(Z=document.createElement("b"),Z.a="_"+ +new Date,Z.innerHTML="<i id='"+Z.a+"'>t</i>",(U=ya.call(document,"#"+Z.a,Z))&&(U="t"==U.innerHTML)||(U=s));X=function(){};X.prototype=[];Z=new X;Z.push(1);!Z.length&&!("NodeList"in t)&&(Z=document.createElement("iframe"),Z.style.display="none",document.body.appendChild(Z),Z.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),X=t.NodeList);H||(R="uniqueId");
v||(Qa=function(a){a+="";if(this.querySelectorAll)try{return V(this.querySelectorAll(a.replace(/\s+(?=\S)|^/g,".")))}catch(e){}var f=[],k=this.all,d,h=-1;if(k.length)for(a=RegExp(a.replace(da,ea));d=k[++h];)d.className&&a.test(d.className)&&f.push(d);return f});
ta=S.matches||S.webkitMatchesSelector||S.mozMatchesSelector||S.msMatchesSelector||S.oMatchesSelector||"querySelector"in document?function(a){if(!a)return s;if("*"===a||":root"===a&&this===S||"body"===a&&this===document.body)return n;var e,f,k=s;if(!Ja.test(a)&&(e=this.parentNode)&&"querySelector"in e)k=e.querySelector(a)===this;if(!k&&(e=this.ownerDocument))for(f in a=e.querySelectorAll(a),a)if(Object.prototype.hasOwnProperty.call(a,f)&&(k=a[f]===this))return n;return k}:function(a){if(!a)return s;
if("*"===a||this===S&&":root"===a||this===document.body&&"BODY"===a.toUpperCase())return n;var e,f,k=s,d,a=Ba.call(a);if(e=a.match(Ia))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return(k=!(f=e[2])||this.className&&RegExp(f.replace(ca," ").replace(da,ea)).test(this.className))&&!(f=e[1])||this.tagName&&this.tagName.toUpperCase()===f.toUpperCase()}else{if(Ja.test(a)){f=va.call(this.ownerDocument,a);for(d in f)if(Object.prototype.hasOwnProperty.call(f,d)&&(k=f[d]===this))return n;
return s}f=aa(a.match(Ga),p,s,p,this,n);return f[0]===this}};Z="matchesSelector";S[Z]||(W.matches=S.matches=W[Z]=S[Z]=ta);Z="matches";Z in W||(W[Z]=document.documentElement[Z]=W.matchesSelector);Z="querySelectorAll";W[Z]=S[Z]=document[Z]=function(a,e){return va.call(this,a,s,e)};Z="querySelector";W[Z]=S[Z]=document[Z]=function(a,e){return va.call(this,a,n,e)||p};Z="getElementsByClassName";document[Z]||(W[Z]=S[Z]=document[Z]=Qa);W=Z=g;
})();
