/* MIT License (c) copyright Egor Halimonenko (termi1uc1@gmail.com|github.com/termi) */
;(function(){"use strict";
var g=void 0,j=!0,o=null,p=!1,t=window;
function aa(a,c,d,h,f,x,k){var b=a.match(ba)||[],a=d||[],l=!!f,m=l&&(c={})||(!c?document:"length"in c?c[0]:c),G,H=0,i,D=ca[b[1]||""]||0,ra=2<D,I=b[2],N=!!I,A=b[3],S=!!A,E=b[4],J=!!E,ea="*"===I,v,O,e,T,r,B,z,n,F,fa,q,K,y,s,w,U,V,ga,ha;N&&(I=ea?g:I.replace("|",":").toUpperCase());if(J&&(E=E.replace(da," "),!u||1!==D))fa=RegExp(E.replace(C,L));l&&(D=0);if(l=b[5]){l=ia.call(l,"][");for(v=-1;r=l[++v];)if(r=l[v]=r.match(ja),r[2]=ka[r[2]],(s=r[3])&&" i"==la.call(s,-2))r[3]=s.substr(0,s.length-2),r[4]=j}if(q=
b[6])q=q.match(ma),z=na[q[1]],2>z&&q[2]&&(B=/\D/.test(q[2])?"even"===q[2]?[o,2]:"odd"===q[2]?[o,2,"%",1]:q[2].match(oa):[o,0,"%",q[2]],V=z?"nodeIndexLast":"nodeIndex",ga=z?"lastChild":"firstChild",ha=z?"previousSibling":"nextSibling");if(1==D)if(S){if(pa){f=document.getElementsByName(A);K=[];for(v=-1;b=f[++v];)b.id==A&&K.push(b)}else{K=[];for(f=[];b=document.getElementById(A);)f.push(b),b.id==A&&K.push(b),b.setAttribute("id",A+" _");for(v=-1;b=f[++v];)b.setAttribute("id",A)}f=S=g}else J=J&&!u,N=N&&
u&&!!E;T=(!("length"in c)||1===c.length)&&!h&&!l&&!q&&!N&&!J&&!S;do{b=g;switch(D){case 1:if(A)if(f=[],K.length)for(v=-1;b=K[++v];){if(m===document||m.contains(b))f.push(b),K.splice(v--,1)}else return a;else"BODY"===I&&9===m.nodeType?(f=[m.body],J=!!E,T=T&&!J):f=!E||!u?m.getElementsByTagName(I||"*"):m.getElementsByClassName(E);b=f[0];break;case 2:f=m.children;b=f[0];break;case 3:G=c[H+1];case 4:if(!(b=M(m)))continue}if(T)return f;m=0;if(b){do if(!ea||1===b.nodeType)if(P?!(h&&(O=b[Q])in d):!k||((O=
b[Q])?!(O in k):b[Q]=++qa)){if(e=!(N&&(i=b.nodeName.toUpperCase())!==I||S&&b.id!==A||J&&(!b.className||!fa.test(b.className)))){if(l){v=-1;for(U=b.attributes;e&&(r=l[++v])&&(e=(w=r[1])in U);)if(n=w in sa?sa[w](b):(n=U[w])&&(n.specified||w in ta)&&""!==n.nodeValue?n.nodeValue:o,y=r[2],n===o){if(!(e=8==y))e=p}else switch(r[4]&&(n=n.toUpperCase()),F=r[3],y){case 1:e=!!n||""===n;break;case 2:e=n===F;break;case 3:case 8:e=RegExp("(^| +)"+F+"($| +)").test(n);8==y&&(e=!e);break;case 4:case 5:case 6:s=n.indexOf(F);
e=6===y?~s:5===y?s==n.length-F.length:!s;break;case 7:e=n===F||!!~n.indexOf(F+"-");break;case 9:e=!!~(" "+n.replace(ua," ")+" ").indexOf(" "+F+" ")}}if(e&&q)switch(z){case 0:case 1:if(!B[1]&&!B[3])break;w=b[V]||0;y=B[3]?("%"===B[2]?-1:1)*B[3]:0;s=B[1];if(w)e=!s?!(w+y):!((w+y)%s);else{e=p;i=b.parentNode[ga];do if(1==i.nodeType&&(i[V]=++w)&&b===i&&(!s?!(w+y):!((w+y)%s)))e=j;while(!e&&(i=i[ha]))}break;case 2:case 3:for(i=b;(i=i.previousSibling)&&1!==i.nodeType;);e=!i;if(!e||3==z)break;case 4:e=!M(b);
break;case 5:e="HTML"==(i||b.nodeName.toUpperCase());break;case 6:e=!b.firstChild;break;case 7:e=!!b.checked;break;case 8:e=b.lang==B||R.lang==B;break;case 9:case 10:e="disabled"in b&&"form"in b&&(10==z?b.disabled===j&&"hidden"!==b.type:b.disabled===p);break;case 11:e=b.parentNode.selectedIndex&&!!b.selected;break;case 12:e=!!~(b.textContent||b.data||b.innerText||b.nodeValue||b.value||"").indexOf(q[2]);break;case 13:case 14:e=W.call(b,q[2]);13==z&&(e=!e);break;case 15:case 16:i||(i=b.nodeName.toUpperCase()),
e=("INPUT"==i||"TEXTAREA"==i||b.getAttribute("contenteditable")!==o)&&!b.a,16==z&&(e=!e)}}if(e){if(x)return[b];h?a[O]=b:(k&&(k[O]=j),a.push(b))}i=g}while(b=ra?4===D?g:b===G?g:M(b):f[++m])}}while(m=c[++H]);return a}
function X(a,c,d){d||(d=this);for(var a=va.call(a.replace(wa,"$1")),h=[],f,x=-1,k=d,b,l,m,G=j,H=p,i,D=!!document.querySelector.__noorder__||!!document.querySelectorAll.__noorder__,a=a.replace(xa,"@=").replace(ya,"-child($1%$2)").match(za);f=a[++x];){l=a[x+1];m=!l||","===l.charAt(0);!P&&(l&&1<l.length&&!b)&&(b={});if(!H)if(G&&"nodeType"in d&&9===d.nodeType&&"BODY"===f.toUpperCase())k=[d.body],m&&(h=k);else if(G&&":root"===f)k=[R],m&&(h=k);else if(k&&(!(d=k)||0===k.length))k=o,H=j;else if(!H){if(k=
!D&&P&&m&&(i||!!l||1<d.length))i=j;k=aa(f,d,m?h:[],k,o,c&&lastRul,!P&&(m&&b||!G&&1<d.length&&{}))}if(G=m)!h.length&&k&&(i=p,h=Aa(k)),k=o,d=this,H=p;if(!l||","===l)break}P||h.sort(Ba);return i?Aa(h,j):h}function Ba(a,c){return a===c?0:a.compareDocumentPosition(c)&4?-1:1}t.Element||((t.Element=ActiveXObject).prototype.ie=j);t.HTMLElement||(t.HTMLElement=t.Element);t.Node||(t.Node=t.Element);
var Y=t.Element.prototype,C=/\s*(\S+)\s*/g,L="(?=(^|.*\\s)$1(\\s|$))",Ca=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,wa=/\s*([,>+~ ])\s*/g,xa=/\~\=/g,za=/(^[>+~ ]?|,|\>|\+|~| ).*?(?=[,>+~ ]|$)/g,da=/\./g,ua=/\s/g,ba=/^([,>+~ ])?([\w\-\|\*]*)\#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?:\:(.+))?$/,ja=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$\@!]?=)['"]?(.*?)['"]?)?\]?$/,ma=/^([^(]+)(?:\(([^)]+)\))?$/,ya=/\-child\((\dn)\+(\d)\)/g,oa=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,Da=/([,>+~ ])/,Ea=/^\s+/,Fa=/\s/,ca={"":1," ":1,
",":1,">":2,"~":3,"+":4},ka={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},na={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16},sa={href:function(a){return a.getAttribute("href",2)}},ta={coords:1,id:1,name:1};
function Aa(a,c){var d=a.length>>>0,h=new Z;if(!c){try{Ga.call(a)}catch(f){}if(h&&h.length===d)return h}for(var x=0;x<d;x++)x in a&&h.push(a[x]);return h}var pa,Ha=p,Ia="_"+Math.random(),Ja=document.createElement("br");R.appendChild(Ja).id=Ia;try{Ha=document.getElementsByName(Ia)[0].id===Ia}catch(Ka){Ha=p}finally{R.removeChild(Ja)}pa=Ha;
var Q="sourceIndex",P=Q in R&&!("opera"in t),qa=1,R=document.documentElement,M="nextElementSibling"in R?function(a){return a.nextElementSibling}:function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a},va=String.prototype.trim||function(){for(var a=this.replace(Ea,""),c=a.length;Fa.test(a.charAt(--c)););return a.slice(0,c+1)},ia=String.prototype.split,La=String.prototype.substr,la="b"=="ab".substr(-1)?String.prototype.substr:function(a,c){return La.call(this,0>a?0>(a=this.length+a)?0:a:a,c)},
Ma,u=R.getElementsByClassName&&80>(R.getElementsByClassName+"").length,Ga=Array.prototype.slice,$,Z,W;Z=function(){};Z.prototype=[];$=new Z;$.push(1);!$.length&&!("NodeList"in t)&&($=document.createElement("iframe"),$.style.display="none",document.body.appendChild($),$.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),Z=t.NodeList);P||(Q="uniqueId");
u||(Ma=function(a){a=a+"";if(this.querySelectorAll)try{return Aa(this.querySelectorAll(a.replace(/\s+(?=\S)|^/g,".")))}catch(c){}var d=[],h=this.all,f,x=-1;if(h.length)for(a=RegExp(a.replace(C,L));f=h[++x];)f.className&&a.test(f.className)&&d.push(f);return d});
W=function(a){if(!a)return p;if(a==="*"||this===R&&a===":root"||this===document.body&&a.toUpperCase()==="BODY")return j;var c,d,h=p,f,a=va.call(a);if(c=a.match(Ca))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return(h=!(d=c[2])||this.className&&RegExp(d.replace(da," ").replace(C,L)).test(this.className))&&!(d=c[1])||this.tagName&&this.tagName.toUpperCase()===d.toUpperCase()}else{if(Da.test(a)){d=X.call(this.ownerDocument,a);for(f in d)if(Object.prototype.hasOwnProperty.call(d,
f))if(h=d[f]===this)return j;return p}d=aa(a,o,p,o,this,j);return d[0]===this}};$="matchesSelector";
R[$]||(Y.matches=R.matches=Y[$]=R[$]=Y[$]=R.webkitMatchesSelector||R.mozMatchesSelector||R.msMatchesSelector||R.oMatchesSelector||"querySelector"in document?function(a){if(!a)return p;if(a==="*"||a===":root"&&this===R||a==="body"&&this===document.body)return j;var c,d,h=p;if(!Da.test(a)&&(c=this.parentNode)&&"querySelector"in c)h=c.querySelector(a)===this;if(!h&&(c=this.ownerDocument)){a=c.querySelectorAll(a);for(d in a)if(Object.prototype.hasOwnProperty.call(a,d))if(h=a[d]===this)return j}return h}:
W);$="matches";$ in Y||(Y[$]=document.documentElement[$]=Y.matchesSelector);$="querySelectorAll";document[$]||(Y[$]=R[$]=document[$]=function(a,c){return X.call(this,a,p,c)});$="querySelector";document[$]||(Y[$]=R[$]=document[$]=function(a,c){return X.call(this,a,j,c)[0]||o});$="getElementsByClassName";document[$]||(Y[$]=R[$]=document[$]=Ma);
})();
